project_id = "agsqdznjjxptiyorljtv"

[functions.admin-user-management]
verify_jwt = true

[functions.doodstream-api]
verify_jwt = false

[functions.assign-admin]
verify_jwt = false

[functions.thumbnail-proxy]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-invite]
verify_jwt = true