version: '3.8'

services:
  telegram-userbot:
    build:
      context: ./telegram_userbot
      dockerfile: Dockerfile
    container_name: telegram-userbot
    restart: unless-stopped
    
    # Environment variables (override .env in container)
    environment:
      - LOG_LEVEL=INFO
    
    # Mount configuration and sessions
    volumes:
      - ./telegram_userbot/.env:/app/.env:ro
      - telegram_sessions:/app/.sessions
      - telegram_logs:/app/logs
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Security
    read_only: true
    security_opt:
      - no-new-privileges:true
    user: "1001:1001"
    
    # Temporary filesystems for read-only container
    tmpfs:
      - /tmp
      - /app/.cache
    
    # Health check
    healthcheck:
      test: ["CMD", "python3", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  telegram_sessions:
    driver: local
  telegram_logs:
    driver: local

# Optional: Network isolation
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16