import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import Index from "./pages/Index";
import Login from "./pages/Login";
import Register from "./pages/Register";
import CompleteProfile from "./pages/CompleteProfile";
import ForgotPassword from "./pages/ForgotPassword";
import UpdatePassword from "./pages/UpdatePassword";
import VideoDetail from "./pages/VideoDetail";
import AdminLogin from "./pages/AdminLogin";
import AdminUpload from "./pages/AdminUpload";
import NotFound from "./pages/NotFound";
import Sitemap from "./pages/Sitemap";
import Favorites from "./pages/Favorites";
import Contact from "./pages/Contact";
import Profile from "./pages/Profile";
import Premium from "./pages/Premium";
import ProtectedRoute from "./components/ProtectedRoute";
import ProfileCompleteGuard from "./components/ProfileCompleteGuard";

const queryClient = new QueryClient();

const App = () => (
  <QueryClientProvider client={queryClient}>
    <TooltipProvider>
      <Toaster />
      <Sonner />
      <BrowserRouter future={{ v7_startTransition: true, v7_relativeSplatPath: true }}>
        <ProfileCompleteGuard>
            <Routes>
              <Route path="/" element={<Index />} />
              <Route path="/login" element={<Login />} />
              <Route path="/register" element={<Register />} />
              <Route path="/complete-profile" element={<CompleteProfile />} />
              <Route path="/forgot-password" element={<ForgotPassword />} />
              <Route path="/update-password" element={<UpdatePassword />} />
              <Route path="/admin/login" element={<AdminLogin />} />
              <Route path="/video/:id" element={<VideoDetail />} />
              <Route path="/favorites" element={<Favorites />} />
              <Route path="/profile" element={<Profile />} />
              <Route path="/contact" element={<Contact />} />
              <Route path="/premium" element={<Premium />} />
              <Route path="/sitemap" element={<Sitemap />} />
              <Route path="/sitemap.xml" element={
                <div style={{display: 'none'}}>
                  {/* This route exists for SEO purposes - actual sitemap is generated by edge function */}
                </div>
              } />
              <Route path="/admin/upload" element={
                <ProtectedRoute requireAdmin>
                  <AdminUpload />
                </ProtectedRoute>
              } />
              {/* ADD ALL CUSTOM ROUTES ABOVE THE CATCH-ALL "*" ROUTE */}
              <Route path="*" element={<NotFound />} />
            </Routes>
          </ProfileCompleteGuard>
        </BrowserRouter>
      </TooltipProvider>
  </QueryClientProvider>
);

export default App;