// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agsqdznjjxptiyorljtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnc3Fkem5qanhwdGl5b3JsanR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTAyMTcsImV4cCI6MjA3MTE4NjIxN30.P1KxrXpAB_Qr8vFdsw_dAT2__qgXEKWmqJur7k1NLL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});